import React from "react";
import type { Metadata } from "next";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProjectLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            {children}
        </section>
    );
}
